### ISSUE TITLE
Parameters setting for the released spinnerf dataset

### ISSUE THREAD

**Issue by chenhonghua** [SamsungLabs/SPIn-NeRF#10]
I am trying to reproduce the results on the released spinnerf dataset.
Are there any parameters that need tuning? or just the same as the statue dataset.

**Comment by HannahHaensen** [comment]
@chenhonghua did you had success with this?

**Comment by chenhonghua** [comment]
@HannahHaensen  After several trials, I found some parameters (like near and far) will be adaptively adjusted. Most of them work well.

**Comment by HannahHaensen** [comment]
@chenhonghua for me sometimes the inpainting does not work always did you experience sth similar?

**Comment by ashmrz** [comment]
Hi. The parameters are all set as mentinoned in the paper. We use a resize factor of 4 to avoid memory issues.
