### ISSUE TITLE
Colmap output of spin-nerf-data

### ISSUE THREAD

**Issue by Hendery77** [SamsungLabs/SPIn-NeRF#11]
Thanks for the great work.
I want to ask why both the data of the removed object (GT) and the data of the unremoved object are sent to Colmap to generate the camera pose at the same time.
Shouldn't these two sets of data be sent separately to Colmap to generate the camera pose? 
So when we run the data in the spin nerf dataset, we have to re feed the data of the unmodified object into the colmap for preprocessing once before we can continue running the spin nerf?

**Comment by ashmrz** [comment]
Hi. Sorry for the late reply. We wanted to have both the gt images without the object and the captures with the object to be within the same coordinate system. So we fed all of the images together at the same time to Colmap. As a result of having the shared coordinate system, we can train the inpainted nerf with the images that have the object, and render it from the views that we have captures without the object. Then we can compare the results and have quantitative evaluations.
