### ISSUE TITLE
Datasets on your project page

### ISSUE THREAD

**Issue by luyr** [SamsungLabs/SPIn-NeRF#14]
Hi,
Thank you for your great work! I'm wondering how to get the datasets showed on your project page (e.g. piano)

**Comment by ashmrz** [comment]
Hi, thanks for your kind words. 

Our own dataset in addition to the masks of the scenes used for our multiview segmentation evaluation can be found here: https://drive.google.com/drive/folders/1N7D4-6IutYD40v9lfXGSVbWrd47UdJEC

The piano scene is from the IBRNet dataset, and wasn't part of our own proposed data, thus we haven't released it under our website. Please refer to https://github.com/googleinterns/IBRNet to find it. 

Regards, 
Ashkan

**Comment by Arcxml** [comment]
hello, I want to know how to use llff dataset in Multiview-Segmentation-Data.zip. Could you please help me? @luyr
