### ISSUE TITLE
A question about processing data

### ISSUE THREAD

**Issue by Arcxml** [SamsungLabs/SPIn-NeRF#15]
hello, thanks for your excellent work

but I want to ask how do you process the 360 unbounded scene, I only find LLFF data loading code ....

Thanks a lot

**Comment by ashmrz** [comment]
Hi. Thank you for your kind words. You can use the same colmap script to recover the camera parameters of a 360-unbounded scene in the LLFF format. The same loader then can load the dataset and start the training. However, please notice that at the time of the project, we did not use a NeRF model with scene contraction to handle very far backgrounds. You can potentially add scene contractions to your follow-up implementations/projects to improve the quality in unbounded scenes.

**Comment by Arcxml** [comment]
Thanks for your reply！I have one more question，do you use NDC constraction in your code?  If not，does it mean that the llff datasets don't need any contraction?



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/17/2023 00:21 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [SamsungLabs/SPIn-NeRF] A question about processing data (Issue #15) |

Hi. Thank you for your kind words. You can use the same colmap script to recover the camera parameters of a 360-unbounded scene in the LLFF format. The same loader then can load the dataset and start the training. However, please notice that at the time of the project, we did not use a NeRF model with scene contraction to handle very far backgrounds. You can potentially add scene contractions to your follow-up implementations/projects to improve the quality in unbounded scenes.
