### ISSUE TITLE
Error running run_nerf.py

### ISSUE THREAD

**Issue by davidceka** [SamsungLabs/SPIn-NeRF#18]
Hi! I'm testing your solution on my computer and after installing everything, when i run 

`python DS_NeRF/run_nerf.py --config DS_NeRF/configs/config.txt --render_factor 1 --prepare --i_weight 1000000000 --i_video 1000000000 --i_feat 4000 --N_iters 4001 --expname statue --datadir ./data/statue --factor 2 --N_gt 0`

I get this error: ` File "/home/david/miniconda3/envs/spinnerf/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/david/miniconda3/envs/spinnerf/lib/python3.8/site-packages/cv2/typing/__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
`
Do you have any clue as to why? I found online that i gotta comment that line on the init.py but i don't know, doing that gets me this new error 
`  File "/home/david/miniconda3/envs/spinnerf/lib/python3.8/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/david/miniconda3/envs/spinnerf/lib/python3.8/site-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
TypeError: read() got an unexpected keyword argument 'ignoregamma'
`
So i left it like it was.

Any suggestione?

**Comment by ashmrz** [comment]
Hi. As suggested [here](https://github.com/facebookresearch/nougat/issues/40), this seems like a package version issue with opencv. You're using a later version of the opencv package, and downgrading to version `4.8.0.74` should help fixing the problem.

**Comment by davidceka** [comment]
> Hi. As suggested [here](https://github.com/facebookresearch/nougat/issues/40), this seems like a package version issue with opencv. You're using a later version of the opencv package, and downgrading to version `4.8.0.74` should help fixing the problem.

Hi, thanks for the prompt reply. Is there a list of the specific versions you used that you know are working? just so I can replicate them exactly.
