### ISSUE TITLE
Is there a way to prevent the model from outputting the following information during training

### ISSUE THREAD

**Issue by wuzuyin** [SamsungLabs/SPIn-NeRF#19]
![09b0d1b05524853f8fcd6797ba2d18e](https://github.com/SamsungLabs/SPIn-NeRF/assets/52769308/192768e2-e276-43e3-8e76-cc287ab9039b)

**Comment by ashmrz** [comment]
Hi. 

I'm not sure if the lpips model we use provides a non_verbose setting, but there are ways to reroute stdout with function calls in python you can use while calculating the lpips. 

Regards
