### ISSUE TITLE
How to use mask_refinement.py?

### ISSUE THREAD

**Issue by AIBUWAN** [SamsungLabs/SPIn-NeRF#2]
HI

IN README.md, I don't know  how to use mask_refinement.py? what is its role?

Please explain it. Thanks.

**Comment by ashmrz** [comment]
Hi. Thanks for reaching out. I'll add the instructions for multiview segmentation to the README file soon. For now, providing masks, you can use the mutiview inpainter. I appreciate your patience in the meantime.
