### ISSUE TITLE
Statue Dataset Label All Black

### ISSUE THREAD

**Issue by AnonymousAchilles** [SamsungLabs/SPIn-NeRF#24]
Hi, 
Thank you for releasing the great work on 3D inpainting! However, I encountered an issue with the sample statue dataset, and I found all masks under statue/images_2/label are zero. I wonder if this is expected? Thanks in advance for your response.

**Comment by ashmrz** [comment]
Hi. 

Thanks for your interest in our work. Sorry for the late reply as this repo is no longer active. The masks might seem black if you open them with an image viewer, but if you open them with cv2 or PIL.Image.Open and turn them to np arrays, they have 0 and 1 values. 

Regards
