### ISSUE TITLE
Instruction on how to create other datasets and use MVSeg is desired.

### ISSUE THREAD

**Issue by PatrickDDj** [SamsungLabs/SPIn-NeRF#5]
1. How to create my own dataset? 1)creating masks, 2)officail code for downscaling
2. How to use MVSeg? 1)generate masks from spin-nerf

**Comment by ashmrz** [comment]
Hi. Sorry for the late reply; this repo is no longer maintained. For creating your own dataset, I suggest following the sample data we provide under https://drive.google.com/drive/folders/1N7D4-6IutYD40v9lfXGSVbWrd47UdJEC. For generating masks, you can use any multi-view or image segmentation method of your choice. Only note that after getting the masks, you have to arrange them in the same format as the SPIn-NeRF dataset.
