### ISSUE TITLE
how do you generate the original masks in ./labels ?

### ISSUE THREAD

**Issue by Quyans** [SamsungLabs/SPIn-NeRF#6]
Thanks for the great work. 
I'd like to ask, you said you used a video segment model to finush video segmentation. Which model did you use? Can you point out
the github repo? thanks

**Comment by HannahHaensen** [comment]
I would be interested in that too! @Quyans do you have new insights on this one?

**Comment by Quyans** [comment]
已收到邮件

**Comment by ashmrz** [comment]
Hi. As mentioned in the paper, we use Dino video segmentation for that task. For the initial object mask, we used EdgeFlow, but now SAM (Segment anything model) is out and can be used too.

**Comment by Quyans** [comment]
已收到邮件
