### ISSUE TITLE
Output contains artifacts in first stage

### ISSUE THREAD

**Issue by UdonDa** [SamsungLabs/SPIn-NeRF#7]
Hi, @ashmrz 

Thank you for sharing your excellent work!
I'm trying to reproduce your result. I can reproduce your result using the "statue" scene.

But, using other scenes, NeRF in the first stage contains artifacts. If I understand correctly, NeRF in the first stage aims to produce depth maps, so it should be trained using only non-inpainted images with masks.
Currently, I have two problems. I describe these problems below.

### 1. When no implementations are changed.
This way loads 100 images including GT images. For GT images, all pixels are masked-out following [this line](https://github.com/SamsungLabs/SPIn-NeRF/blob/master/DS_NeRF/load_llff.py#L165) (I'm not sure).
Then, I obtained the result below.  A target object, which is a watering can, is semi-transparent. I think GT images that include no target bring a leak in the results.

https://github.com/SamsungLabs/SPIn-NeRF/assets/25411643/d8765011-6596-46cd-a2fe-f737c7a233ec

### 2. Only using 60 images.
The provided camera parameters are optimized using 100 images by COLMAP as described in a log of COLMAP in `spinnerf-dataset/${scene}/colmap_output.txt`. So, just changing to use 60 images is an unanticipated implementation method. Actually, as shown in the video, the result looks very bad.

If I re-generate camera parameters using 60 images, your method could work well like the statue scene. But, it contradicts the published COLMAP information.

https://github.com/SamsungLabs/SPIn-NeRF/assets/25411643/01a9ce47-d2c3-49e9-ad88-520058e65e7c

### Question
Is the method of estimating camera parameters using COLMAP with only 60 images (problem 2) the correct way to reproduce your method?

I apologize in advance if my understanding is incorrect.

**Comment by UdonDa** [comment]
I think the problem lies in the way the training and test sets are split up [here](https://github.com/SamsungLabs/SPIn-NeRF/blob/master/DS_NeRF/run_nerf.py#L1030).

The below command works well like the video. I just modify `--N_gt 0` to `--N_gt 40` because the first 40 images in the image county are test images.
```
python DS_NeRF/run_nerf.py --config DS_NeRF/configs/config.txt --render_factor 1 --prepare --i_weight 1000000000 --i_video 1000000000 --i_feat 4000 --N_iters 4001 --expname statue --datadir ./data/statue --factor 2 --N_gt 40
```

In your README, you specify `--N_gt 0` while `N_gt=40` in [config.txt](https://github.com/SamsungLabs/SPIn-NeRF/blob/master/DS_NeRF/configs/config.txt#L4). I guess you made a mistake with README.

https://github.com/SamsungLabs/SPIn-NeRF/assets/25411643/12bc4c3b-f695-4360-84cd-39b8c1ef392e

**Comment by HannahHaensen** [comment]
@UdonDa 

hey when i use the traiining command for the spin-nerf dataset i get the command killed? although on the statue it worked perfectly

i also tried your command but i face the same issue, did you had the same problem?


`Loaded llff (100, 2268, 4032, 3) (120, 3, 5) [2268.     4032.     1534.5869] ./data/spinnerf-dataset/1
Auto LLFF holdout, 1000000
DEFINING BOUNDS
NEAR FAR 1.200000035762787 7.736926078796387
Found ckpts []
Not ndc!
get rays
done, concats
rays_rgb.shape and labels.shape: (100, 3, 2268, 4032, 3) (100, 3, 2268, 4032, 1) (100, 2268, 4032, 3) (100, 2268, 4032) (100, 3, 4)
Killed
`

**Comment by UdonDa** [comment]
The loaded tensor looks good. I didn’t encounter the killer problem.
Sorry for not suggesting a correct answer to your problem.

**Comment by HannahHaensen** [comment]
@UdonDa fixed it was sth weird with mogrify

**Comment by UdonDa** [comment]
Congrats! Could you release your re-produced code?

**Comment by HannahHaensen** [comment]
@UdonDa for me resizing works now it was jsut png/jpeg problem, but for the inpaining so far I can only reproduce the statue results for the rest the inpainint does not work completly, and i am not so sure why

**Comment by indigopyj** [comment]
@UdonDa  Did you solve the problem?
