### ISSUE TITLE
Output size is too small

### ISSUE THREAD

**Issue by BloodLemonS** [SamsungLabs/SPIn-NeRF#9]
How to solve the following problem when running on a 3070 laptop?
RuntimeError: Given input size: (256x1x2). Calculated output size: (256x0x1). Output size is too small.

**Comment by ashmrz** [comment]
Hi. Could you elaborate on the problem? Where is the line of code that gives you the error?

**Comment by BloodLemonS** [comment]
The specific location of the problem is shown in the figure below. I think this is a problem with my own dataset, so I would like to ask if there is a detailed method for creating a dataset? If there are any relevant steps and reference documents, we look forward to your reply
![2023-10-09 16-30-00屏幕截图](https://github.com/SamsungLabs/SPIn-NeRF/assets/56753880/b151e5a8-10dd-47e5-a39d-942501584684)
